#!/bin/bash
#File has various options to give the current dir, diplay home dir,
#and to list the current directory's contents.
clear
echo "Please select a menu item..."
echo
echo "1) Display your current directory"
echo "2) Display your home directory"
echo "3) List the contents of your current directory"
echo
read CHOICE
if [ $CHOICE = 1 ]
then
pwd
fi
if [ $CHOICE = 2 ]
then 
echo $HOME
fi 
if [ $CHOICE = 3 ]
then
ls
fi
echo
echo "Have a great day!"
